### ISSUE TITLE
install_node v8.9.1 returns in checksum error

### ISSUE THREAD

**Issue by hrgui** [GoogleCloudPlatform/nodejs-docker#149]
Not sure if this is the right location for this, but upon upgrading from node 8.7.0 to 8.9.1 with the custom dockerfile option, I received the following error:

```
Step 2/4 : RUN install_node v8.9.1 --ignore-verification-failure
 ---> Running in 62247bf0359c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.0M  100 17.0M    0     0  5638k      0  0:00:03  0:00:03 --:--:-- 5639k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4551  100  4551    0     0  15336      0 --:--:-- --:--:-- --:--:-- 15323
gpg: Signature made Tue Nov 7 22:39:17 2017 UTC using RSA key ID 821C587A gpg: Can't check signature: public key not found
The Node.js binary could not be verified.
This means it may not be an officially released Node.js binary
or may have been tampered with.

The installation will continue because the --ignore-verification-failure
flag was specified, but it is strongly recommended that you install
a version of Node.js that can been verified.
```

The workaround I had to do is: `--ignore-verification-failure`, which is fine - but i'm just wondering how and where this should be updated / or is there something wrong on my end when downloading this.

**Comment by DominicKramer** [comment]
Hi.  Yes, this is the right location, and thanks for letting us know about this.  Unfortunately, I am not able to reproduce the issue you are seeing.

That is, I have a `server.js` file that is a simple Hello World app.  My `app.yaml` file is as follows:
```yaml
env: flex
runtime: custom
```
and my `Dockerfile` is as follows:
```Dockerfile
FROM gcr.io/google-appengine/nodejs
RUN install_node 8.7.0
RUN install_node 8.9.1
COPY . /app/
RUN npm install --unsafe-perm || \
  ((if [ -f npm-debug.log ]; then \
      cat npm-debug.log; \
    fi) && false)
CMD node server.js
```
When I run `gcloud app deploy`, the app deploys fine.  That is, I don't encounter any errors when verifying the Node.js 8.9.1 binary.

Note that the latest `gcr.io/google-appengine/nodejs` image already has Node 8.9.1 installed, and so you don't need to install it manually.

If you would like to install it manually (for example to remain at Node 8.9.1 even when the `gcr.io/google-appengine/nodejs` image upgrades to the next Node version), I have a few thoughts on what the problem could be:
1. The `FROM` line in your Dockerfile could be referencing an older `gcr.io/google-appengine/nodejs` image.
2. Your `gcloud` might need to be updated. Use `gcloud components update` to update.
3. There was an error in downloading the binary that caused the verification checks to correctly fail.

If none of these help, please let me know, and I can investigate further.  Thanks.

**Comment by hrgui** [comment]
Thanks @DominicKramer - problem is now solved. the solution is:

The FROM line needed to be updated - it was `FROM launcher.gcr.io/google/nodejs`. I updated it to `FROM gcr.io/google-appengine/nodejs`

I also ran a test by installing node v9.2.0, and that worked. 

----

For reference, my dockerfile looked like this:
```docker
FROM launcher.gcr.io/google/nodejs

# Install node.js 4.6.1
RUN install_node v8.9.1 --ignore-verification-failure

# Copy application code.
COPY . /app/

# Install dependencies.
RUN npm --unsafe-perm install
```

**Comment by DominicKramer** [comment]
@hrgui I'm glad you were able to resolve your issue, and thank you for pointing out the issue with `launcher.gcr.io/google/nodejs` being out of sync.
