### ISSUE TITLE
migration to Node v8 LTS?

### ISSUE THREAD

**Issue by The-Alchemist** [GoogleCloudPlatform/nodejs-docker#154]
Node v6 will cease being in active maintenance mode in April 2018.  Was wondering if these was a plan to migrate to Node v8 LTS around that time?  Or earlier?

Thanks!

P.S. I'm using Google Cloud Functions, which use v6.11.5 ATM.

**Comment by ofrobots** [comment]
Hi @The-Alchemist. Thanks for opening the issue! This docker image is used as the default for App Engine Flexible environment, and already defaults to the [latest version of 8.x LTS](https://github.com/GoogleCloudPlatform/nodejs-docker/blob/e580490fb40f68b8549ef29f852573065e1312f3/runtime-image/Dockerfile#L22-L26). My understanding is that the Google Cloud Functions team is looking at expanding support for Node 8.x, but I am not familiar with any detailed plans from their side, however. I have forwarded your request to the Cloud Functions team.

I'm going to close this issue, as this is not an issue/bug in this particular repository. If this doesn't adequately address your question/concern, please add a comment / reopen. Thanks!

**Comment by The-Alchemist** [comment]
@ofrobots : Thank you for the response, and my apologies for posting on the wrong repo.  I thought this was the docker image that Google Cloud Functions used.  If you know of the docker image that they use and could point me in that direction, that would be awesome!

**Comment by ofrobots** [comment]
Hi @The-Alchemist sorry for the late reply. Cloud Functions uses a docker image that is similar to the one in this repo, but they do not have an external repository for it. I've forwarded your feedback to the Cloud Functions team internally.

**Comment by The-Alchemist** [comment]
@ofrobots : Thanks for the info!  I'll just keep my eyes on the Cloud Functions release notes.
