### ISSUE TITLE
Can't install newer versions of Node.js

### ISSUE THREAD

**Issue by lostpebble** [GoogleCloudPlatform/nodejs-docker#173]
As per the instructions at the bottom of the ReadMe for changing the Node.js version:

```
FROM launcher.gcr.io/google/nodejs

# Install node.js 4.6.1
RUN install_node v4.6.1

# Copy application code.
COPY . /app/

# Install dependencies.
RUN npm --unsafe-perm install
```

I've tried to change that to (the latest version of Node):

```
RUN install_node v10.6.0
```

And also:

```
RUN install_node v9.11.2
```

And both times I've got the result (with the relevant version number):

```
Step #2: Node installation failed: No Node.js version satisfying v10.6.0 found.
Step #2: The command '/bin/sh -c install_node v10.6.0' returned a non-zero code: 1
Finished Step #2
```

Some other's I've tried now which are not working either:

9.11.1
9.11.0

I've even tried with the `--ignore-verification-failure` option.

The latest version that still seems to work is 9.10.1.

**Comment by lostpebble** [comment]
```
function getAvailableVersions(cb) {
  request(
    'GET', 'storage.googleapis.com', '/gae_node_packages/node_versions',
    function(err, body) {
      if (err) {
        return cb(err);
      }
      return cb(null, body.trim().split('\n').sort().reverse());
    }
  );
}
```

This is the culprit.

It would appear that the script verifies available versions from a static file of version numbers... This file has obviously not been updated.

This is the file it downloads: http://storage.googleapis.com/gae_node_packages/node_versions

I've been searching for ways this script could be updated to always be able to get the latest versions without having to rely on a static file (I'm unsure how that is kept updated... seems like something manually triggered or entered).

The best I've found so far is this: https://nodejs.org/dist/index.json

It is a JSON array which lists every version of Node.js ascending from the latest one.

**Comment by lostpebble** [comment]
My current workaround for anyone who runs into this.

Replace the `RUN install_node` step with this:

```
# Install node.js
RUN /opt/gcp/runtime/bootstrap_node \
    --direct \
    --ignore-verification-failure \
    v10.6.0
```

This is what `install_node` uses behind the scenes. Although it is probably less safe because we are forcing it to download a direct version from Node.js servers and ignoring verification (The verification code doesn't seemed to have caught up with the current versions so there's not much we can do).

**Comment by ofrobots** [comment]
Thanks for opening the bug @lostpebble. We'll take a look.

**Comment by dlorenc** [comment]
This should be fixed nowl. We had an issue with our automation so I ran the job manually. We'll make sure it's running continuously again.

**Comment by dlorenc** [comment]
```shell
$ gsutil cat gs://gae_node_packages/node_versions | grep v9.1
v9.1.0
v9.1.0
v9.10.0
v9.10.0
v9.10.1
v9.10.1
v9.11.0
v9.11.0
v9.11.1
v9.11.1
v9.11.2
v9.11.2
```
