### ISSUE TITLE
Support Monorepo

### ISSUE THREAD

**Issue by odanado** [GoogleCloudPlatform/nodejs-docker#199]
In a builder image, `node_modules` is assumed it is in the root directory.
https://github.com/GoogleCloudPlatform/nodejs-docker/blob/06f8ed69210f72c28d5be5ad53b4ba339591b7d7/builder/steps/gen-dockerfile/contents/data/Dockerfile.txt#L26
But, in monorepo `node_modules` is appeared in a various directory hierarchy. For example, `/frontend/node_modules` , `/packages/package-name/node_modules` and etc.

I got the following error when I deploy to GAE a web application that is managed monorepo.
```bash
error building image: error building stage: symlink /app/backend/node_modules/nodemon/bin/nodemon.js /app/backend/node_modules/.bin/nodemon: file exists
```
The reason for the error is that the builder can't delete `backend/node_modules`.

**Comment by jahjahbin** [comment]
I believe we won't fix this. We are actively maintaining a new build workflow [1, 2], if you are on GAE Flex we recommend upgrading to newer Node versions (i.e. 18 or 20) and raising issues on the new GitHub repo[2] if you have feature requests, bugs, etc.

[1] https://cloud.google.com/appengine/docs/flexible/nodejs/runtime
[2] https://github.com/GoogleCloudPlatform/buildpacks
