### ISSUE TITLE
ADD step copies local node_modules to the container

### ISSUE THREAD

**Issue by Guuz** [GoogleCloudPlatform/nodejs-docker#22]
Hello,

On line 6 of the dockerfile (https://github.com/GoogleCloudPlatform/nodejs-docker/blob/master/runtime/Dockerfile#L6) the local app files are added to the container. In the steps before the right `node_module` folder has been created.
But the step on line 6 will copy your (dirty) local `node_modules` over the (clean) container `node_modules`.
This is very bad for so many reasons! ;-)

ps. i'm using managed vm's with custom runtimes; a `.dockerignore` file does not work.
ps2. I accidentally also posted this issue at the docker repository github page. But this is actually relevant for both. See https://github.com/dockerfile/nodejs-runtime/issues/2

**Comment by JustinBeckwith** [comment]
I believe this is addressed.  Feel free to re-open if this is still an issue.
