### ISSUE TITLE
Pulling Node Over HTTP?

### ISSUE THREAD

**Issue by ClashTheBunny** [GoogleCloudPlatform/nodejs-docker#23]
Seems like a major security problem.

**Comment by proppy** [comment]
HTTPS would be better, additional we could also verify the md5sum of each release, see https://github.com/joyent/docker-node/blob/master/0.11/slim/Dockerfile#L20

I'd recommend also reporting that issue against the official node image repository https://github.com/joyent/docker-node now maintained by joyent.

**Comment by ClashTheBunny** [comment]
They don't need to, they verify the image with GPG signed SHA1 sums, which they receive the keys for it over https.  Their solution is fairly elegant.  Why they don't store the GPG keys in the repo, beats me.  I still would trust a ssh received git repo more than an ssl received GPG key.

**Comment by JustinBeckwith** [comment]
We're using HTTPS now:
https://github.com/GoogleCloudPlatform/nodejs-docker/blob/master/base/Dockerfile#L9
