### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by manoj150283** [GoogleCloudPlatform/nodejs-docker#25]
I am running this image for my nodejs application but after every 5-6 request, my node server is getting crashed. After going through the error log, I found it is throwing Segmentation fault (core dumped) error.

**Comment by proppy** [comment]
do you have the same issue outside of docker?

**Comment by JustinBeckwith** [comment]
Let us know if this is something you'd like us to take a look at.
