### ISSUE TITLE
npm install --production

### ISSUE THREAD

**Issue by Guuz** [GoogleCloudPlatform/nodejs-docker#27]
Hello,

I already submitted this a long time ago, but in the wrong repository... My bad!
https://github.com/dockerfile/nodejs-runtime/issues/1

---

I think you actually want to run `npm install --production` instead of `npm install`. This decreases the size of projects that use separate dependencies and devDependencies in the `package.json`. This is pretty common.
If that somehow does not make sense for this image; how can i achieve this for my project? Can i overwrite certain commands or should i use my own fork of this docker file?

Thanks for the help!

**Comment by proppy** [comment]
as a workaround you could do `FROM google/nodejs` and do the `RUN npm install yourself`.

I would also recommend starting this discussion on the official node image repository https://github.com/joyent/docker-node now maintained by joyent.

**Comment by Guuz** [comment]
Yup, that is what we are doing now. But i think the default should be a production install due to how the dependencies and devDependencies work in NPM. Then this benefits all. And if someone for some reason wants to deploy a version with devDependencies he/she can use the workaround.

This is what we use: (striped down of some lines that only apply to us)
```
# Pull base image.
FROM google/nodejs

# Define working directory.
WORKDIR /app

# Copy only the package.json file for npm install.
ADD package.json /app/

# Install dependencies in production mode (no dev dependencies).
RUN npm install --production

# Make the app run in production mode.
ENV NODE_ENV production

# Copy app files.
ADD . /app

# Expose ports.
EXPOSE 8080
```

**Comment by JustinBeckwith** [comment]
I believe setting NODE_ENV to production also impacts npm install.  This won't install dev dependencies:

    $ NODE_ENV production npm install 

Today we set NODE_ENV before running npm install:
https://github.com/GoogleCloudPlatform/nodejs-docker/blob/master/base/Dockerfile#L13

We're actually considering changing this to make it easier to use tools like grunt and gulp.

**Comment by adambuczynski** [comment]
+1, one year later the script still runs `npm install` as opposed to `npm install --production`, which brings in so many unused and redundant node modules...

**Comment by JustinBeckwith** [comment]
If we run `npm install --production` by default, users won't get devDependencies.  I get that it adds a lot of modules - but right now it's the only way to run a `postinstall` script.  A lot of users want to postinstall run gulp or grunt.

**Comment by adambuczynski** [comment]
@JustinBeckwith is it possible to somehow have this controlled via a setting in `app.yaml`? Currently, the only work around is making a custom Dockerfile, but that doesn't seem optimal either as for some reason when I do that I lose all console logging output during the deployment process.

**Comment by ofrobots** [comment]
Going through old issues. Today the runtime, by default has `NODE_ENV` set to `production` which effectively means that `npm install` is equivalent to `npm install --production`. This means that `devDependencies` do NOT get installed by default. 

We do have plans to add better support for multi-stage builds to make it easier to run post install / build steps, but that seems outside the scope of the original issue here.

I am closing this for now. If there were other concerns that I missed, please reopen.
