### ISSUE TITLE
Upgrade to 0.12.7

### ISSUE THREAD

**Issue by PranceTheDeer** [GoogleCloudPlatform/nodejs-docker#31]
Are there any plans to upgrade the docker image to support node 0.12.7?  I think a lot of people are itching to try the new ECMAScript 6 features.  I'm already creating a small forked patch if you want to pull that in later.

**Comment by JustinBeckwith** [comment]
You can now use the engines field to specify a nodejs runtime which will be installed at runtime:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/express/package.json

**Comment by ArtworkAD** [comment]
@JustinBeckwith this is not working because npm is not checking the engines property

- https://github.com/npm/npm/issues/12486
- https://stackoverflow.com/questions/44133856/how-to-install-other-than-lts-version-of-node-on-google-app-engine-instance
