### ISSUE TITLE
Upgrade or allow option to run newer node version (5.0)

### ISSUE THREAD

**Issue by silenceisgolden** [GoogleCloudPlatform/nodejs-docker#36]
I believe I am running in to an error when I'm trying to get started with nodejs on GAE (again). I need the most updated version of node, but the one on the server I believe is 0.12.7. Current LTS is 4.2.1 and current version is 5.0.0. Is there a way to opt into a newer version of node or a plan to upgrade to the newest version?

**Comment by JustinBeckwith** [comment]
You can now use any feature you would like via the engines field:

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/express/package.json
