### ISSUE TITLE
Node installation should use a verified binary package

### ISSUE THREAD

**Issue by raggi** [GoogleCloudPlatform/nodejs-docker#48]
Today we're assuming that https means package verification, which is not true.

See https://github.com/GoogleCloudPlatform/nodejs-docker/blob/master/base/Dockerfile#L9

We should be doing at least one of:
- Use a well known SHA to verify the package against a known, externally verified package
- Import a known verified package into the repo and use that to build
- Use a package manager based install that includes package native verification

3 will probably be easiest and would assist with future upgrades.

**Comment by ofrobots** [comment]
WIP: https://github.com/ofrobots/nodejs-docker/commits/nvm
/cc @justinbeckwith

**Comment by raggi** [comment]
NVM doesn't do any verification either.

**Comment by ofrobots** [comment]
It does: https://github.com/creationix/nvm/blob/master/nvm.sh#L1005

**Comment by raggi** [comment]
That's almost entirely useless. If I scanned the code correctly it fetches the shasum from the same mirror that it fetched the file from. All it does is provide some integrity assurance, it does not provide any verification of the contents of the package or the authority of the mirror.

**Comment by ofrobots** [comment]
I believe this is fixed via #74 now.
