### ISSUE TITLE
Not setting NODE_ENV to production.

### ISSUE THREAD

**Issue by hhhonzik** [GoogleCloudPlatform/nodejs-docker#56]
Hey,

I have a project which is deployed to GAE and is using this image as base, but i want to deploy a dev version of this app. 

I've created a simple `app-dev.yaml` file, which looks like this:

```
service: dev-api
runtime: custom
vm: true
threadsafe: false

env_variables:
  NODE_ENV: development
```

But it isn't picked up by Dockerfile, is there any way to work around this?

**Comment by JustinBeckwith** [comment]
Interesting - we'll do some testing to figure out why this isn't working.  In the meantime - can you try setting the env var via your Dockerfile?  Try adding this:

```dockerfile
ENV NODE_ENV production
```

My guess is that we have a bug with the interaction between env vars set by Flex and env vars set in the base dockerfile.

**Comment by hhhonzik** [comment]
Thanks @JustinBeckwith for the answer. 

I think we are talking about 2 issues now, 

1) is setting `NODE_ENV` in [Dockerfile](https://github.com/GoogleCloudPlatform/nodejs-docker/blob/master/base/Dockerfile#L19) (rewrite any value it has from `app.yaml` file)

2) Not propagating any values from `app.yaml` file. The first issue is probably blocked by this too. I tried all the other `ARG` commands, but nothing helped. Example:

app.yaml
```
runtime: custom
vm: true

env_variables:
  MY_VAR: test
```

Dockerfile
```
FROM gcr.io/google_appengine/nodejs

# not in a list
RUN export

# empty
RUN echo ${MY_VAR}
```


Also, your workaround can't work in case I am having 2 *app-production.yaml* and *app-development.yaml* files and deploy accordingly. 

Setting environment in Dockerfile doesn't help me (I can't have multiple Dockerfiles).

**Comment by ofrobots** [comment]
@hhhonzik Is there a specific reason why you are using `runtime: custom`. If you use `runtime: nodejs`, your `NODE_ENV` env. var. should get respected.

app-development.yaml
```yaml
runtime: nodejs
vm: true
env_variables:
  NODE_ENV: development
```

Can you give this a try? We will independently investigate why the NODE_ENV environment variable doesn't get picked up with `runtime: custom`.

**Comment by hhhonzik** [comment]
Hey @ofrobots, unfortunately, we need to use `runtime: custom` because our node.js application uses imagemagick and some private git modules (so i need to install SSH keys before running `npm install`)

I've decided I'll wait until this issue is resolved and keep my code on GCE for now.

**Comment by ofrobots** [comment]
@hhhonzik Would you be able to describe your workflow a bit more? Are you running the docker images locally inside docker, or are you deploying the `app-*.yaml` file to AppEngine and not seeing the environment variable take effect?

When I deploy applications to AppEngine, I do see the environment variables from `app-*.yaml` take effect. Here's my setup:

app-debug.yaml:
```yaml
runtime: custom
vm: true
env_variables:
  NODE_ENV: development
```

index.js:
```js
var express = require('express');
var app = express();
app.get('/', function (req, res) {
  res.send('NODE_ENV is ' + process.env.NODE_ENV + '\n');
});
app.listen(process.env.PORT || 8080, function () {
  console.log('Example app listening');
});
```

```bash
$ gcloud app deploy app-debug.yaml
...

$ curl https://${my-project-name}.appspot.com
NODE_ENV is development

$ gcloud app deploy app-production.yaml
...

$ curl https://${my-project-name}.appspot.com
NODE_ENV is production
```

**Comment by ofrobots** [comment]
The env_variables mechanism should allow you to set the NODE_ENV value to appropriate value. Feel free to re-open if this doesn't work for you.

Oh, btw, the default Node.js image for AppEngine now includes `imagemagick` by default in case that helps you decide :smile:.

**Comment by RawanHerzallah** [comment]
Hi,
I've been trying to pass env_variables from the app.yaml with cutom runtime to the dockerFile  and the value I read for it is empty, any advice ?
```
23:48:19 env_variables:
23:48:19   JETTY_ARGS: -Djava.util.logging.config.file=WEB-INF/flex.logging.properties
23:48:19   NODE_NAME: sre-testing-metricbeat
```

However, when i try to read its value i see it empty:
```
23:50:46 [INFO] GCLOUD: Step 14/21 : RUN echo "__________________ $NODE_NAME ____________"
23:50:46 [INFO] GCLOUD:  ---> Running in 41737ae048df
23:50:46 [INFO] GCLOUD: __________________  ____________
```
